// <auto-generated />
using System;
using LibraryManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeApp;

#nullable disable

namespace PracticeApp.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20251029090801_Books_link")]
    partial class Books_link
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticeApp.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("StudentId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Valmiki",
                            AvailableCopies = 5,
                            BookName = "Ramayan",
                            StudentId = 1
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Anne Frank",
                            AvailableCopies = 5,
                            BookName = "Diary of a Young girl"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Sudha Murthy",
                            AvailableCopies = 5,
                            BookName = "House of cards",
                            StudentId = 5
                        },
                        new
                        {
                            BookId = 4,
                            Author = "A.P.J Abdul Kalam",
                            AvailableCopies = 5,
                            BookName = "Wings of Fire"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Shiv Khera",
                            AvailableCopies = 5,
                            BookName = "You can win"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Veda Vyas",
                            AvailableCopies = 5,
                            BookName = "Mahabharat"
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.BookDTO", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OverdueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BookId");

                    b.ToTable("BookDTO");
                });

            modelBuilder.Entity("PracticeApp.Models.BorrowedBook", b =>
                {
                    b.Property<int>("BorrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowId"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("bookDtoBookId")
                        .HasColumnType("int");

                    b.Property<int>("studentDtoId")
                        .HasColumnType("int");

                    b.HasKey("BorrowId");

                    b.HasIndex("bookDtoBookId");

                    b.HasIndex("studentDtoId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("PracticeApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "CSE",
                            Email = "Akash@gmail.com",
                            Phone = "9876543212",
                            StudentName = "Akash",
                            Year = 1
                        },
                        new
                        {
                            Id = 2,
                            Department = "ECE",
                            Email = "Goutham@gmail.com",
                            Phone = "9321456708",
                            StudentName = "Goutham",
                            Year = 3
                        },
                        new
                        {
                            Id = 3,
                            Department = "EEE",
                            Email = "Karthik@gmail.com",
                            Phone = "8759543212",
                            StudentName = "Karthik",
                            Year = 2
                        },
                        new
                        {
                            Id = 4,
                            Department = "MECH",
                            Email = "Darshan@gmail.com",
                            Phone = "9892826312",
                            StudentName = "Darshan",
                            Year = 1
                        },
                        new
                        {
                            Id = 5,
                            Department = "CSE",
                            Email = "Arjun@gmail.com",
                            Phone = "9874853212",
                            StudentName = "Arjun",
                            Year = 4
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.StudentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentDTO");
                });

            modelBuilder.Entity("PracticeApp.Models.Book", b =>
                {
                    b.HasOne("PracticeApp.Models.Student", "Student")
                        .WithMany("Books")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PracticeApp.Models.BorrowedBook", b =>
                {
                    b.HasOne("PracticeApp.Models.BookDTO", "bookDto")
                        .WithMany()
                        .HasForeignKey("bookDtoBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeApp.Models.StudentDTO", "studentDto")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("studentDtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bookDto");

                    b.Navigation("studentDto");
                });

            modelBuilder.Entity("PracticeApp.Models.Student", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PracticeApp.Models.StudentDTO", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
