// <auto-generated />
using LibraryManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeApp;

#nullable disable

namespace PracticeApp.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20251103060203_HashedPassword")]
    partial class HashedPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStudent", b =>
                {
                    b.Property<int>("BooksBookId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("BooksBookId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("StudentBooks", (string)null);
                });

            modelBuilder.Entity("PracticeApp.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admin", (string)null);

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Designation = "Librarian",
                            Password = "$2a$11$dxuext4uhGVzGXagEEokAuubco82PFGJ/r3NUBlAGGfZbYKPAnvVa",
                            UserName = "Aravind"
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Valmiki",
                            AvailableCopies = 10,
                            BookName = "Ramayan"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Anne Frank",
                            AvailableCopies = 10,
                            BookName = "Diary of a Young girl"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Sudha Murthy",
                            AvailableCopies = 10,
                            BookName = "House of cards"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "A.P.J Abdul Kalam",
                            AvailableCopies = 10,
                            BookName = "Wings of Fire"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Shiv Khera",
                            AvailableCopies = 10,
                            BookName = "You can win"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Veda Vyas",
                            AvailableCopies = 10,
                            BookName = "Mahabharat"
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "CSE",
                            Email = "Akash@gmail.com",
                            Password = "$2a$11$ihw92xRpkLKOAWEeiTyFGudhXZwWRAChINOS46/iUKL7UYDqTKU4y",
                            Phone = "9876543212",
                            StudentName = "Akash",
                            Year = 1
                        },
                        new
                        {
                            Id = 2,
                            Department = "ECE",
                            Email = "Goutham@gmail.com",
                            Password = "$2a$11$8fAxrH35.wJ2T9nOUKXnKu/68M1yNMqijLsGInsKiVXqprG0R61ei",
                            Phone = "9321456708",
                            StudentName = "Goutham",
                            Year = 3
                        },
                        new
                        {
                            Id = 3,
                            Department = "EEE",
                            Email = "Karthik@gmail.com",
                            Password = "$2a$11$e/qVQIU.yBbKE2kyf1X1Q.eDU83zIgIVW7P6noboxvgrSdq3EuMIG",
                            Phone = "8759543212",
                            StudentName = "Karthik",
                            Year = 2
                        },
                        new
                        {
                            Id = 4,
                            Department = "MECH",
                            Email = "Darshan@gmail.com",
                            Password = "$2a$11$RPk4GlH4T4JHcDLg.kfL8uts1iA31pzjQ9g6NlXm5PD0D7mTQUywm",
                            Phone = "9892826312",
                            StudentName = "Darshan",
                            Year = 1
                        },
                        new
                        {
                            Id = 5,
                            Department = "CSE",
                            Email = "Arjun@gmail.com",
                            Password = "$2a$11$1dZ2f7RNRvpcZg8cQDwPJOOmU8Q9/MDW9UjEiBjAy3bYOgtx5Kxee",
                            Phone = "9874853212",
                            StudentName = "Arjun",
                            Year = 4
                        });
                });

            modelBuilder.Entity("BookStudent", b =>
                {
                    b.HasOne("PracticeApp.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeApp.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
