// <auto-generated />
using System;
using LibraryManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PracticeApp.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20251017044425_AddedBookToStudent")]
    partial class AddedBookToStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticeApp.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("StudentId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Valmiki",
                            BookName = "Ramayan",
                            StudentId = 3
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Anne Frank",
                            BookName = "Diary of a Young girl",
                            StudentId = 1
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Sudha Murthy",
                            BookName = "House of cards",
                            StudentId = 2
                        },
                        new
                        {
                            BookId = 4,
                            Author = "A.P.J Abdul Kalam",
                            BookName = "Wings of Fire"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Shiv Khera",
                            BookName = "You can win",
                            StudentId = 5
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Veda Vyas",
                            BookName = "Mahabharat"
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bookname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BorrowedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OverdueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowedDate = new DateTime(2025, 10, 17, 4, 44, 24, 792, DateTimeKind.Utc).AddTicks(4288),
                            Department = "CSE",
                            OverdueDate = new DateTime(2025, 10, 27, 10, 14, 24, 792, DateTimeKind.Local).AddTicks(4295),
                            StudentName = "A",
                            Year = 1
                        },
                        new
                        {
                            Id = 2,
                            BorrowedDate = new DateTime(2025, 10, 17, 4, 44, 24, 792, DateTimeKind.Utc).AddTicks(4316),
                            Department = "ECE",
                            OverdueDate = new DateTime(2025, 10, 27, 10, 14, 24, 792, DateTimeKind.Local).AddTicks(4317),
                            StudentName = "B",
                            Year = 3
                        },
                        new
                        {
                            Id = 3,
                            BorrowedDate = new DateTime(2025, 10, 17, 4, 44, 24, 792, DateTimeKind.Utc).AddTicks(4319),
                            Department = "EEE",
                            OverdueDate = new DateTime(2025, 10, 27, 10, 14, 24, 792, DateTimeKind.Local).AddTicks(4319),
                            StudentName = "C",
                            Year = 2
                        },
                        new
                        {
                            Id = 4,
                            BorrowedDate = new DateTime(2025, 10, 17, 4, 44, 24, 792, DateTimeKind.Utc).AddTicks(4320),
                            Department = "MECH",
                            OverdueDate = new DateTime(2025, 10, 27, 10, 14, 24, 792, DateTimeKind.Local).AddTicks(4321),
                            StudentName = "D",
                            Year = 1
                        },
                        new
                        {
                            Id = 5,
                            BorrowedDate = new DateTime(2025, 10, 17, 4, 44, 24, 792, DateTimeKind.Utc).AddTicks(4322),
                            Department = "CSE",
                            OverdueDate = new DateTime(2025, 10, 27, 10, 14, 24, 792, DateTimeKind.Local).AddTicks(4322),
                            StudentName = "E",
                            Year = 4
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.Book", b =>
                {
                    b.HasOne("PracticeApp.Models.Student", "StudPossessing")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("StudPossessing");
                });
#pragma warning restore 612, 618
        }
    }
}
