// <auto-generated />
using LibraryManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeApp;

#nullable disable

namespace PracticeApp.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20251104062720_BorrowedBookTable")]
    partial class BorrowedBookTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticeApp.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admin", (string)null);

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Designation = "Librarian",
                            Password = "$2a$11$1SN7OrcSK9PC8r9ub7A6fO77il8.xxOzl/MyjolSFBX0LbXRpQm66",
                            UserName = "Aravind"
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Valmiki",
                            AvailableCopies = 10,
                            BookName = "Ramayan"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Anne Frank",
                            AvailableCopies = 10,
                            BookName = "Diary of a Young girl"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Sudha Murthy",
                            AvailableCopies = 10,
                            BookName = "House of cards"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "A.P.J Abdul Kalam",
                            AvailableCopies = 10,
                            BookName = "Wings of Fire"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Shiv Khera",
                            AvailableCopies = 10,
                            BookName = "You can win"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Veda Vyas",
                            AvailableCopies = 10,
                            BookName = "Mahabharat"
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.BorrowedBook", b =>
                {
                    b.Property<int>("BorrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowId"));

                    b.Property<string>("BorrowedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverdueOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bookId")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.HasKey("BorrowId");

                    b.HasIndex("bookId");

                    b.HasIndex("studentId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("PracticeApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "CSE",
                            Email = "Akash@gmail.com",
                            Password = "$2a$11$xY8Qejm9yMhsuKJPyMgM0u1YeAnyTQLM5nS.6irf.NOoy3e45J3ku",
                            Phone = "9876543212",
                            StudentName = "Akash",
                            Year = 1
                        },
                        new
                        {
                            Id = 2,
                            Department = "ECE",
                            Email = "Goutham@gmail.com",
                            Password = "$2a$11$g0IfIQZAEz3mwB1njzl99O2VHRjZ0xrYzj/Ug6HUkBOdVFhdbw7PS",
                            Phone = "9321456708",
                            StudentName = "Goutham",
                            Year = 3
                        },
                        new
                        {
                            Id = 3,
                            Department = "EEE",
                            Email = "Karthik@gmail.com",
                            Password = "$2a$11$HZut1rIxhQqGFQkpPbxgW.eUFbH4sxMBfIv6DSSpa9.U5tZIu90Ya",
                            Phone = "8759543212",
                            StudentName = "Karthik",
                            Year = 2
                        },
                        new
                        {
                            Id = 4,
                            Department = "MECH",
                            Email = "Darshan@gmail.com",
                            Password = "$2a$11$MxbbMBibzWfnBuFHbnpuPOh5EKi6d664Ds5YkgzRsD5W.hjvBEuGS",
                            Phone = "9892826312",
                            StudentName = "Darshan",
                            Year = 1
                        },
                        new
                        {
                            Id = 5,
                            Department = "CSE",
                            Email = "Arjun@gmail.com",
                            Password = "$2a$11$S8ZC6Ggbl2P3tP5CGq9Oi.oRBHZ8YmkzA9yRBXquNyWB9neWXCwe6",
                            Phone = "9874853212",
                            StudentName = "Arjun",
                            Year = 4
                        });
                });

            modelBuilder.Entity("PracticeApp.Models.BorrowedBook", b =>
                {
                    b.HasOne("PracticeApp.Models.Book", "book")
                        .WithMany("BorrowedList")
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeApp.Models.Student", "student")
                        .WithMany("BorrowedList")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");

                    b.Navigation("student");
                });

            modelBuilder.Entity("PracticeApp.Models.Book", b =>
                {
                    b.Navigation("BorrowedList");
                });

            modelBuilder.Entity("PracticeApp.Models.Student", b =>
                {
                    b.Navigation("BorrowedList");
                });
#pragma warning restore 612, 618
        }
    }
}
